#!/bin/bash
iptables -t filter -F
iptables -t nat -F
iptables -t mangle -F
 		 	
echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE

iptables -t filter -A INPUT -M STATE --state RELATED,ESTABLISHED -j ACCEPT
iptables -t filter -A OUTPUT -M STATE --state RELATED,ESTABLISHED -j ACCEPT
iptables -t filter -A FORWARD -M STATE --state RELATED,ESTABLISHED -j ACCEPT

############################Regra##########################

#liberar acesso da rede interna apenas por ssh,http,dns,snmp,ping e ftp
  #liberando acesso via ssh para o servidor.
  iptables -t filter -A INPUT -i eth0 -m state NEW -p tcp --dport 222 -j ACCEPT
  
  #Liberando o acesso http da rede interna para o servidor.
  iptables -t filter -A INPUT -i eth0 -m state NEW -p tcp --dport 80 -j ACCEPT
  
  #Liberar a rede interna requisitar dns para o servidor.
  iptables -t filter -A INPUT -i eth0 -m state NEW -p udp --dport 53 -j ACCEPT

  #liberando a rede interna acessar o servidor via snmp.
  iptables -t filter -A INPUT -i eth0 -m state NEW -p udp --dport 161 -j ACCEPT

  #Liberando o servidor fazer requisitos icmp.
  iptables -t filter -A INPUT -p icmp --icmp-type echo-request -j ACCEPT
  #liberar a rede interna pingar para o servidor
  iptables -t filter -A INPUT -i eth0 -p icmp --icmp-type echo-reply -j ACCEPT

  #liberando ftp da rede interna para o servidor.
  iptables -t filter -A INPUT -i eth0 -m state NEW multiport -p tcp --dport 20,21 -j ACCEPT

#Liberar a rede interna para navegação via http's.(Http=80|Https=443)
  #Liberando http's para rede interna.
  iptables -t filter -A FORWARD -i eth0 -m state NEW multiport -p tcp --dport 80,443 -j ACCEPT
  
#Liberando resolução de nomes apenas pelo dns publico da google.
  iptables -t filter -A FORWARD -i eth0 -m state NEW -p udp --dport 53 -j ACCEPT

#Permitir ping apenas para ip da Uol e gateway do Senac.
  #Ip da Uol
  iptables -t filter -A FORWARD -p icmp --icmp-type echo-request -d 200.221.2.45 -j ACCEPT
  
  #Gateway do SENAC.
  iptables -t filter -A FORWARD -p icmp --icmp-type echo-request -d 172.16.3.254 -j ACCEPT
  iptables -t filter -A FORWARD -p icmp --icmp-type echo-reply -s 172.16.3.254 -j ACCEPT
  
#Registrar em LOG todas as tentativas de log SMTP (25,587,468)
  iptables -t filter -A INPUT -i eth0 -p tcp -m multiport --dport 25,587,468 -j LOG
  
#Permitir o servidor firewall acesse web, pingue no gateway do Senac e tenha acesso total a qualquer maquina interna. 
  #Permitindo o servidor Acessar Web (http, https e dns)
  iptables -t filter -A INPUT  -i eth1 -o eth1 -p tcp -m state NEW multiport  --dport 80,443 -j ACCEPT
 
  #Permitindo o servidor pingar para o gateway do senac.
  iptables -t filter -A OUTPUT -m state NEW -p icmp --icmp-type echo-request -d 172.16.3.254 -j ACCEPT
  
  #Permitindo o servidor tenha acesso total a qualquer maquina interna.
  iptables -t filter -A OUTPUT -o eth0 -j ACCEPT
  #Sem ações sobre o comando acima.
 
 #Registrar em log qualquer acesso da rede interna que não seja de navegação.
  iptables -t filter -A FORWARD -i eth0 !-p tcp -m --dport 88,443 -j LOG
  
   #Regras NAT
  
 #A saida da porta 25 será pelo IP 172.16.2.52
  iptables -t nat -A PREROUTING -p tcp --dport 25 -o eth1 -j DNAT --to 172.16.2.52
 
#Uma estação específica da rede saia pelo IP 172.16.2.51
  iptables -t nat -A POSTROUTING -s 10.30.10.54 -j SNAT --to 172.16.2.51
  
#Todo tráfego que chegar no IP 172.16.2.51 caia na máquina acima.
  iptables -t nat -A POSTROUTING -s 172.16.2.51 -j SNAT --to 10.30.10.54
#Apontar portas 80, 443, 20 e 21 para servidor web, entrando pelo IP 172.16.2.50
  iptables -t nat -A POSTROUTING -i eth1 -p tcp -m multiport --dport  443,80,21,20 -j SNAT 10.30.10.50
  
 #Proxy transparente das portas 80, 8080, 1080, 3128 e 443 para próprio servidor na porta 3128
 iptables -t nat -A PREROUTING -i eth0 -p tcp -m multiport --dport 8080,3128,1080,443,80 -j REDIRECT - --to-port 3128 
 
 #Apontar porta 3389 para servidor de TS, entrando pelo 3º IP na porta 5000
iptables -t nat -A POSTROUTING -p tcp --dport 3389 -j SNAT --to 10.30.10.18-3389
